index:
   path: /
   controller: App\Controller\AccueilController::index

portfolio:
   path: /portfolio
   controller: App\Controller\PortfolioController::index
   
AP1:
   path: /AP1
   controller: App\Controller\PortfolioController::afficheAP1

AP2:
   path: /AP2
   controller: App\Controller\PortfolioController::afficheAP2
   
   
stage2:
   path: /stage2
   controller: App\Controller\PortfolioController::afficheStage2   

stage1:
   path: /stage1
   controller: App\Controller\PortfolioController::afficheStage1  
   

veille:
   path: /veille
   controller: App\Controller\VeilleController::index
   